source_dir: '/scratch/p290820/datasets/003_umcg_pst_ksps'        # Where the kspace data is stored
do_make_dicom_like: true                                         # Make recon dicom-like based on shape from header information
target_only: false                                               # only process the target
log_dir: '/scratch/hb-pca-rad/projects/03_nki_reader_study/logs' # The path to the log directory

# The path to the database file. The database contains information about the kspace, dicom and patient information
db_fpath: '/scratch/p290820/datasets/003_umcg_pst_ksps/database/dbs/master_habrok_20231106_v2.db'

# Where the inference files of the vsharp model are stored. This folder should contain patient dirs with predicted .h5 files
prediction_dirs:
  1x: '/scratch/hb-pca-rad/projects/03_nki_reader_study/output/umcg/1x'
  3x: '/scratch/hb-pca-rad/projects/03_nki_reader_study/output/umcg/3x'
  6x: '/scratch/hb-pca-rad/projects/03_nki_reader_study/output/umcg/6x'

# instead of working with exclusion we work with inclusion.
inclusion_list: #null
  # - "0001"
  # - "0002"
  # - "0003"
  # - "0004"
  # - "0005"
  # - "0006"
  # - "0007"
 #### - "0008"      # t2ddicom with adc/dwi=ACCEPTABLE | recon with t2dicom=EXTRA_CHECK    (EXTRA CHECK = GOOD)
  # - "0009"
  # - "0010"
  # - "0011"
  # - "0012"
  # - "0013"
  # - "0014"
  # - "0015"
  # - "0016"
  # - "0017"
  # - "0018"
  # - "0019"
  # - "0020"
  # - "0021"
  # - "0022"
  # - "0023"
  # - "0024"
  # - "0025"
 #### - "0026"      # t2ddicom with adc/dwi=ACCEPTABLE | recon with t2dicom=WRONG   (FIX ATTEMPT)
  # - "0027"
  # - "0028"
  # - "0029"
  # - "0030"
  # - "0031"
  # - "0032"
  # - "0033"
  # - "0034"
  # - "0035"
  # - "0036"
  # - "0037"
  - "0038"
  # - "0039"
  # - "0040"
  # - "0041"
  # - "0042"
####  - "0043"      # t2ddicom with adc/dwi=GOOD | recon with t2dicom=GOOD
  # - "0044"
  # - "0045"
  # - "0046"
####  - "0047"      # t2ddicom with adc/dwi=GOOD | recon with t2dicom=ACCEPTABLE
  # - "0048"
  # - "0049"
  # - "0050"
  # - "0051"
  # - "0052"
  # - "0053"
  # - "0054"
  # - "0055"
  # - "0056"
  # - "0057"
####  - "0058"      # t2ddicom with adc/dwi=EXTRA_CHECK | recon with t2dicom=WRONG    (SEEMS FINE NOW)     
  # - "0059"
  # - "0060"
  # - "0061"
  # - "0062"
  # - "0063"
  # - "0064"
  # - "0065"
  # - "0066"
  # - "0067"
####  - "0068"      # t2ddicom with adc/dwi=GOOD | recon with t2dicom=ACCEPTABLE     (CHECK SEEMS FINE)
  # - "0069"
  # - "0070"
  # - "0071"
  # - "0072"
  # - "0073"
  # - "0074"
  # - "0075"
  # - "0076"
####  - "0077"      # t2ddicom with adc/dwi=ACCEPTABLE | recon with t2dicom=ACCEPTABLE    (SEEMS FINE, dicom seems blurry but not the recon)
  # - "0078"
  # - "0079"
  # - "0080"
  # - "0081"
  # - "0082"
#### - "0083"       # t2ddicom with adc/dwi=GOOD | recon with t2dicom=GOOD
  # - "0084"
  # - "0085"
  # - "0086"
  # - "0087"
  # - "0088"
  # - "0089"
  # - "0090"
  # - "0091"
  # - "0092"
  # - "0093"
  # - "0094"
  # - "0095"
  # - "0096"
####  - "0097"      # t2ddicom with adc/dwi=GOOD | recon with t2dicom=ACCEPTABLE             (CHECK SEEMS FINE)
  # - "0098"
  # - "0099"
  # - "0100"
  # - "0101"
  # - "0102"
  # - "0103"
  # - "0104"
  # - "0105"
  # - "0106"
  # - "0107"
  # - "0108"
  # - "0109"
  # - "0110"
  # - "0111"
  # - "0112"
  # - "0113"
  # - "0114"
  # - "0115"
  # - "0116"
  # - "0117"
  # - "0118"
  # - "0119"
  # - "0120"
  # - "0121"
  # - "0122"
  # - "0123"
####  - "0124"      # t2ddicom with adc/dwi=GOOD | recon with t2dicom=GOOD   (CHECK SEEMS FINE)     
  # - "0125"
  # - "0126"
  # - "0127"
  # - "0128"
  - "0129"
  # - "0130"
  # - "0131"
  # - "0132"
  # - "0133"
  # - "0134"
####  - "0135"        # t2ddicom with adc/dwi=GOOD | recon with t2dicom=GOOD
  # - "0136"
  # - "0137"
  # - "0138"
  # - "0139"
  # - "0140"
  # - "0141"
  # - "0142"
  # - "0143"   
  # - "0144"
  # - "0145"
  # - "0146"
  # - "0147"
  # - "0148" 
  # - "0149"
  # - "0150"
  # - "0151"
####  - "0152"      # t2ddicom with adc/dwi=GOOD | recon with t2dicom=GOOD
  # - "0153"
  # - "0154"
  # - "0155"
  # - "0156"
  # - "0157"
  # - "0158"
  # - "0159"
  # - "0160"
  # - "0161"
  # - "0162"
  # - "0163"
  # - "0164"
  # - "0165"
  # - "0166"
  # - "0167"
  # - "0168"
  # - "0169"
  # - "0170"
  # - "0171"
  # - "0172"