# Where the kspace data is stored
source_dir: '/scratch/p290820/datasets/003_umcg_pst_ksps'

# Where the inference files of the vsharp model are stored. This folder should contain patient dirs with predicted .h5 files
prediction_dir: '/scratch/p290820/projects/03_nki_reader_study/output/umcg/3x'

# Make the reconstruction similar to a dicom based on she shape of the dicom and header information
make_dicom_like: true

# only process the target
target_only: false

# Start post-processing from this patient id. If 0, start from the first patient
# start_from_pat_id: 150

# The following patients are excluded from post-processing
exclusion_list: null
  # - "0063_ANON9972960"  # This patient has a different number of slices in kspace as the corresponding dicoms and nifti. We might have selected the wrong kspace for this patient.
  # - "0151_ANON4277586"  # This patient has a different number of slices in kspace as the corresponding dicoms and nifti. We might have selected the wrong kspace for this patient.

logdir: '/scratch/p290820/projects/03_nki_reader_study/logs'

# The path to the database folder and db itself
db_fpath: '/scratch/p290820/datasets/003_umcg_pst_ksps/database/dbs/master_habrok_20231106_v2.db'

# instead of working with exclusion we work with inclusion.
inclusion_list: #null
  # - "0001"
  # - "0002"
  # - "0003"
  # - "0004"
  # - "0005"
  # - "0006"
  # - "0007"
  # - "0008"
  # - "0009"
  # - "0010"
  # - "0011"
  # - "0012"
  # - "0013"
  # - "0014"
  # - "0015"
  # - "0016"
  # - "0017"
  # - "0018"
  # - "0019"
  # - "0020"
  # - "0021"
  # - "0022"
  # - "0023"
  # - "0024"
  # - "0025"
  # - "0026"
  # - "0027"
  # - "0028"
  # - "0029"
  # - "0030"
  # - "0031"
  # - "0032"
  # - "0033"
  # - "0034"
  # - "0035"
  # - "0036"
  # - "0037"
  # - "0038"
  # - "0039"
  # - "0040"
  # - "0041"
  # - "0042"
  # - "0043"
  # - "0044"
  # - "0045"
  # - "0046"
  # - "0047"
  # - "0048"
  # - "0049"
  # - "0050"
  # - "0051"
  # - "0052"
  # - "0053"
  # - "0054"
  # - "0055"
  # - "0056"
  # - "0057"
  # - "0058"
  # - "0059"
  # - "0060"
  # - "0061"
  # - "0062"
  # - "0063"
  # - "0064"
  # - "0065"
  # - "0066"
  # - "0067"
  # - "0068"
  # - "0069"
  # - "0070"
  # - "0071"
  # - "0072"
  # - "0073"
  # - "0074"
  # - "0075"
  # - "0076"
  # - "0077"
  # - "0078"
  # - "0079"
  # - "0080"
  # - "0081"
  # - "0082"
  # - "0083"
  # - "0084"
  # - "0085"
  # - "0086"
  # - "0087"
  # - "0088"
  # - "0089"
  # - "0090"
  # - "0091"
  # - "0092"
  # - "0093"
  # - "0094"
  # - "0095"
  # - "0096"
  # - "0097"
  # - "0098"
  # - "0099"
  # - "0100"
  # - "0101"
  # - "0102"
  # - "0103"
  # - "0104"
  # - "0105"
  # - "0106"
  # - "0107"
  # - "0108"
  # - "0109"
  # - "0110"
  # - "0111"
  # - "0112"
  # - "0113"
  # - "0114"
  # - "0115"
  # - "0116"
  # - "0117"
  # - "0118"
  # - "0119"
  # - "0120"
  # - "0121"
  # - "0122"
  # - "0123"
  # - "0124"
  # - "0125"
  # - "0126"
  # - "0127"
  # - "0128"
  - "0129"
  # - "0130"
  # - "0131"
  # - "0132"
  # - "0133"
  # - "0134"
  # - "0135"
  # - "0136"
  # - "0137"
  # - "0138"
  # - "0139"
  # - "0140"
  # - "0141"
  # - "0142"
  # - "0143"    # has multiple study dates that interfered.
  # - "0144"
  # - "0145"
  # - "0146"
  # - "0147"    # has multiple study dates that interfered.
  # - "0148"    # has multiple study dates that interfered. 
  # - "0149"    # has multiple study dates that interfered.
  # - "0150"
  # - "0151"    # has multiple study dates that interfered.
  # - "0152"
  # - "0153"
  # - "0154"
  # - "0155"
  # - "0156"
  # - "0157"
  # - "0158"      # has multiple study dates that interfered.
  # - "0159"      # has multiple study dates that interfered.
  # - "0160"
  # - "0161"      # has multiple study dates that interfered.
  # - "0162"
  # - "0163"
  # - "0164"  # has multiple study dates that interfered.
  # - "0165"
  # - "0166"
  # - "0167"
  # - "0168"
  # - "0169"
  # - "0170"  # has multiple study dates that interfered.
  # - "0171"  # has multiple study dates that interfered.
  # - "0172"  # has multiple study dates that interfered.